"""
Django settings for reservation_project.

Generated by 'django-admin startproject' using Django 4.x.

For more information on this file, see
https://docs.djangoproject.com/en/4.x/topics/settings/

"""

import os
from pathlib import Path
import environ
import dj_database_url

env = environ.Env()
# ...existing code...
DEBUG = env.bool('DEBUG', default=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file for local development
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.x/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-test-key-local-123')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}', 'https://terratokenx.onrender.com', 'https://terratokenx-q7u4.onrender.com']
else:
    CSRF_TRUSTED_ORIGINS = ['https://terratokenx.onrender.com', 'https://terratokenx-q7u4.onrender.com']

ALLOWED_HOSTS.append('terratokenx-q7u4.onrender.com')

# Configuración de Seguridad para Producción
if not DEBUG:
    # URL del Admin Oculta (Definida en env o default seguro aleatorio)
    ADMIN_URL = env('ADMIN_URL', default='admin-seguro/')
    
    # HTTPS y Cookies Seguras
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    ADMIN_URL = 'admin/'

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',  # Añadir django-import-export
    'booking',       # Ruta a la app booking
    'django.contrib.humanize',
    'widget_tweaks',
    'corsheaders',  # CORS Headers
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS Middleware must be first
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración CORS para pruebas locales
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'reservation_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'booking', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reservation_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.x/ref/settings/#databases

# Creamos una ruta persistente para la base de datos en Render
DATA_DIR = BASE_DIR / 'data'
DATA_DIR.mkdir(exist_ok=True)

DATABASES = {
    # La configuración por defecto es para producción, usando la variable de entorno DATABASE_URL.
    # dj-database-url se encargará de todo.
    'default': dj_database_url.config(default=f"sqlite:///{DATA_DIR / 'db.sqlite3'}", conn_max_age=600)
}



# Password validation
# https://docs.djangoproject.com/en/4.x/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.x/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.x/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directorio donde se recopilarán los archivos estáticos

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/4.x/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#mercado pago configuración
MERCADO_PAGO_PUBLIC_KEY = env('MERCADO_PAGO_PUBLIC_KEY', default='TEST_PUBLIC_KEY')
MERCADO_PAGO_ACCESS_TOKEN = env('MERCADO_PAGO_ACCESS_TOKEN', default='TEST_ACCESS_TOKEN')

# Configuración de Correo (SendGrid Web API)
# Usamos Web API en lugar de SMTP porque Render bloquea el puerto 587
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='SG.dummy-key-for-local-dev')
CRYPTOMKT_API_KEY = env('CRYPTOMKT_API_KEY', default='')
CRYPTOMKT_API_SECRET = env('CRYPTOMKT_API_SECRET', default='')

# Static Wallet Addresses (Fallback if API key lacks Wallet permissions)
CRYPTOMKT_WALLET_ETH = env('CRYPTOMKT_WALLET_ETH', default='0x498Ea2a861165362D0Ee55D9F3195B3e4FC68a73')
CRYPTOMKT_WALLET_BTC = env('CRYPTOMKT_WALLET_BTC', default='bc1ql4gja2w9ge27a28hhfcq0rx3m8z24m7sjl6a8d')
CRYPTOMKT_WALLET_USDT = env('CRYPTOMKT_WALLET_USDT', default='0x498Ea2a861165362D0Ee55D9F3195B3e4FC68a73')
CRYPTOMKT_WALLET_XLM = env('CRYPTOMKT_WALLET_XLM', default='')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Enviar emails reales incluso en DEBUG

# Email remitente (DEBE coincidir con el Single Sender verificado en SendGrid)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='contacto@terratokenx.com')

# --- URLs de Autenticación ---
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/' # Redirigir a la página principal después de cerrar sesión

# Configuración para archivos media (Imágenes subidas)
MEDIA_URL = '/media/'
# Usar disco persistente de Render si está configurado, sino usar local
RENDER_DISK_PATH = env('RENDER_DISK_PATH', default='')
if RENDER_DISK_PATH:
    MEDIA_ROOT = RENDER_DISK_PATH
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- FirmaVirtual / Trámit Express Integration ---
# IMPORTANTE: En producción, TODAS estas variables deben estar en el entorno
FIRMAVIRTUAL_BASE_URL = env('FIRMAVIRTUAL_BASE_URL', default='https://api.firmavirtual.legal')
# Credenciales - SIN defaults para forzar configuración en producción
FIRMAVIRTUAL_USER = env('FIRMAVIRTUAL_USER', default='')
FIRMAVIRTUAL_PASS = env('FIRMAVIRTUAL_PASS', default='')
# Callback URL para webhooks (debe coincidir con tu dominio en producción)
TRAMIT_CALLBACK_URL = env('TRAMIT_CALLBACK_URL', default='')
FIRMAVIRTUAL_CALLBACK_URL = TRAMIT_CALLBACK_URL
# Modo Prueba: True = NO cobra, False = SÍ cobra
# Cambiar a False cuando quieras empezar a facturar
FIRMAVIRTUAL_TEST_MODE = env.bool('FIRMAVIRTUAL_TEST_MODE', default=True)
