# Generated by Django 5.2.3 on 2025-12-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('MP', 'Mercado Pago'), ('CRYPTO', 'CryptoMarket')], default='MP', max_length=10, verbose_name='Método de Pago'),
        ),
    ]
