# Generated by Django 5.2.3 on 2026-01-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='crypto_address',
            field=models.CharField(blank=True, help_text='Dirección de depósito asignada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Monto exacto esperado en crypto', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='crypto_currency',
            field=models.CharField(blank=True, help_text='Ej: ETH, BTC', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='payment_window_start',
            field=models.DateTimeField(blank=True, help_text='Inicio de la ventana de espera del pago', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
