# Generated by Django 5.2.3 on 2026-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reserva_crypto_address_reserva_crypto_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pagado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('CONFIRMADO', 'Confirmado')], default='PENDIENTE', max_length=15, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('MP', 'Mercado Pago'), ('CRYPTO', 'CryptoMarket'), ('CRYPTO_MANUAL', 'Crypto (Manual)')], default='MP', max_length=15, verbose_name='Método de Pago'),
        ),
    ]
