# Generated by Django 5.2.3 on 2026-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='precio_base_token',
            field=models.PositiveIntegerField(default=100, verbose_name='Precio Base Token (USD)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
