# Generated by Django 5.2.3 on 2026-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_change_total_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tokens_totales',
            field=models.PositiveIntegerField(default=1500, verbose_name='Tokens Totales del Proyecto'),
        ),
    ]
