# Generated by Django 5.2.3 on 2026-01-11 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_add_tokens_totales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL amigable (ej: refugio-patagonia)', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(default='Patagonia Chilena', max_length=200)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('precio_token', models.PositiveIntegerField(default=100, help_text='Precio por token en USD')),
                ('tokens_totales', models.PositiveIntegerField(default=1500)),
                ('rentabilidad_estimada', models.CharField(default='12-18% Anual', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Visible en la web')),
                ('financiamiento_activo', models.BooleanField(default=True, help_text='Permite comprar tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tokens_totales',
            field=models.PositiveIntegerField(default=1500, verbose_name='Tokens Totales del Proyecto (Deprecado)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_set', to='booking.proyecto'),
        ),
    ]
