# Generated by Django 5.2.3 on 2026-01-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_proyecto_alter_configuracion_tokens_totales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Proximamente', 'Próximamente'), ('Vendido', 'Vendido')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pagina_oficial_url',
            field=models.URLField(blank=True, help_text='Enlace a la página oficial del proyecto', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Terreno', 'Terreno'), ('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Campo', 'Campo'), ('Negocio', 'Negocio')], default='Terreno', max_length=20),
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/galeria/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='booking.proyecto')),
            ],
        ),
    ]
