# Generated by Django 5.2.3 on 2026-01-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_proyecto_estado_proyecto_pagina_oficial_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_portada_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen (opcional, ahorra espacio)', null=True),
        ),
        migrations.AddField(
            model_name='proyectoimagen',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen', null=True),
        ),
        migrations.AlterField(
            model_name='proyectoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/galeria/'),
        ),
    ]
