# Generated by Django 5.2.3 on 2026-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_proyecto_imagen_portada_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video del proyecto (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
