# Generated by Django 5.2.3 on 2026-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_proyecto_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cargo_representante',
            field=models.CharField(blank=True, help_text='Ej: Gerente General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contrato_firmado',
            field=models.FileField(blank=True, null=True, upload_to='contratos_firmados/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_empresa',
            field=models.BooleanField(default=False, verbose_name='¿Es Persona Jurídica?'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='firmavirtual_files_ids',
            field=models.JSONField(blank=True, default=list, help_text='IDs de archivos asociados'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='firmavirtual_id',
            field=models.CharField(blank=True, help_text='ID del trámite en FV (request_id)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='firmavirtual_status',
            field=models.CharField(default='pending', help_text='Estado: pending, signed, rejected', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='firmavirtual_url',
            field=models.URLField(blank=True, help_text='Link para firmar', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Solo si es empresa', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT de quien firma (Persona o Rep. Legal)', max_length=20, null=True, verbose_name='RUT Firmante'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut_empresa',
            field=models.CharField(blank=True, help_text='RUT de la empresa', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, help_text='Fundamental para FirmaVirtual', max_length=20, null=True),
        ),
    ]
