# Generated by Django 5.2.3 on 2026-01-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_reserva_cargo_representante_reserva_contrato_firmado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tab (ej: Resumen, Análisis, Números)', max_length=100)),
                ('icono', models.CharField(blank=True, help_text='Emoji o nombre de icono (ej: 📊, description)', max_length=50, null=True)),
                ('contenido', models.TextField(help_text='Contenido de la sección (puede ser HTML)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='booking.proyecto')),
            ],
            options={
                'verbose_name': 'Sección de Proyecto',
                'verbose_name_plural': 'Secciones de Proyecto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
