# Generated by Django 5.2.3 on 2026-02-02 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_proyectoseccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BRONZE', 'Bronze - Explorer'), ('SILVER', 'Silver - Pioneer'), ('GOLD', 'Gold - Builder'), ('BLACK', 'Black - VIP')], max_length=20, unique=True)),
                ('precio_por_1000_creditos', models.PositiveIntegerField(help_text='Costo en USD para obtener 1000 créditos')),
                ('cap_creditos', models.PositiveIntegerField(help_text='Límite máximo de créditos que puede tener la wallet')),
                ('descuento_fees', models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento en fees')),
                ('kyc_requerido', models.CharField(default='V0', help_text='Nivel de KYC mínimo requerido (V0-V4)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Positivo=Acredita, Negativo=Debita', max_digits=12)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra de Paquete'), ('USO', 'Uso en Reserva'), ('EXPIRACION', 'Expiración de Créditos'), ('BONO', 'Bono / Ajuste Admin')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Solo para abonos', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Drop 1 - Early Adopters'", max_length=100)),
                ('porcentaje_stock', models.PositiveIntegerField(help_text='% del stock total que se libera en este drop (ej: 30)')),
                ('descuento_extra', models.PositiveIntegerField(default=0, help_text='% de descuento adicional sobre el precio base')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_solicitado', models.PositiveIntegerField(default=2)),
                ('documento_frente', models.ImageField(help_text='DNI/Pasaporte Frente', upload_to='kyc/')),
                ('documento_reverso', models.ImageField(blank=True, help_text='DNI Reverso (opcional si es pasaporte)', null=True, upload_to='kyc/')),
                ('selfie', models.ImageField(help_text='Foto selfie sosteniendo el documento', upload_to='kyc/')),
                ('origen_fondos', models.TextField(blank=True, help_text='Declaración de origen de fondos (Requerido para V3+)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Admin (Razón rechazo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='BRONZE', max_length=10)),
                ('saldo_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Créditos (USD)')),
                ('kyc_level', models.PositiveIntegerField(default=0, help_text='0=Nuevo, 1=Básico, 2=Standard, 3=Enhanced, 4=Institucional')),
                ('kyc_status', models.CharField(default='NONE', help_text='NONE, PENDING, APPROVED, REJECTED', max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
