# Generated by Django 5.2.3 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_tierconfig_credittransaction_drop_kycapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transacción de Crédito', 'verbose_name_plural': 'Transacciones de Créditos'},
        ),
        migrations.AlterModelOptions(
            name='drop',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Drop', 'verbose_name_plural': 'Drops'},
        ),
        migrations.AlterModelOptions(
            name='kycapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud KYC', 'verbose_name_plural': 'Solicitudes KYC'},
        ),
        migrations.AlterModelOptions(
            name='tierconfig',
            options={'verbose_name': 'Configuración de Tier', 'verbose_name_plural': 'Configuración de Tiers'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('MP', 'Mercado Pago'), ('CRYPTO', 'Crypto'), ('TRANSFER', 'Transferencia Bancaria'), ('MANUAL', 'Asignación Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='ID de transacción MP/Crypto/etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tierconfig',
            name='autoservicio',
            field=models.BooleanField(default=True, help_text='True = compra online, False = requiere WhatsApp/concierge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extension_usada',
            field=models.BooleanField(default=False, help_text='¿Ya usó la extensión 12→18 meses?'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='fecha_expiracion',
            field=models.DateField(blank=True, help_text='Fecha de expiración (solo para abonos)', null=True),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drop',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='booking.proyecto'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas del Admin'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tierconfig',
            name='descuento_fees',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento en fees de plataforma'),
        ),
        migrations.AlterField(
            model_name='tierconfig',
            name='precio_por_1000_creditos',
            field=models.PositiveIntegerField(help_text='Costo en USD para obtener 1000 créditos (ej: 900, 800, 700, 600)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('NONE', 'Sin verificar'), ('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
