# Generated by Django 5.2.3 on 2026-02-03 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_credittransaction_options_alter_drop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='check_risk',
            field=models.BooleanField(default=False, verbose_name='Acepto Risk Disclosure'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='check_terms',
            field=models.BooleanField(default=False, verbose_name='Acepto Términos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='check_utility',
            field=models.BooleanField(default=False, verbose_name='Entiendo que es Utility Token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_level',
            field=models.PositiveIntegerField(default=0, help_text='0=Lite, 1=Standard, 2=Aurea, 3=Diamond'),
        ),
        migrations.CreateModel(
            name='ProyectoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='proyectos/dataroom/')),
                ('titulo', models.CharField(max_length=200)),
                ('publico', models.BooleanField(default=False, help_text='Visible sin login')),
                ('requiere_nda', models.BooleanField(default=False, help_text='Requiere aceptar NDA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='booking.proyecto')),
            ],
        ),
    ]
