# Generated by Django 5.2.3 on 2026-02-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_reserva_check_risk_reserva_check_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='proyectos/documentos/')),
                ('es_publico', models.BooleanField(default=True, verbose_name='¿Es público?')),
                ('requiere_nda', models.BooleanField(default=False, verbose_name='¿Requiere NDA?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='booking.proyecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='drop',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proyectofile',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='TierConfig',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='check_risk',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='check_terms',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='check_utility',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.DeleteModel(
            name='Drop',
        ),
        migrations.DeleteModel(
            name='KYCApplication',
        ),
        migrations.DeleteModel(
            name='ProyectoFile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
