# Generated by Django 5.2.3 on 2026-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_proyectodocumento_remove_credittransaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
