# Generated by Django 5.2.3 on 2026-02-05 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_reserva_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('documento_identidad_frontal', models.ImageField(blank=True, null=True, upload_to='kyc/documentos/')),
                ('documento_identidad_reverso', models.ImageField(blank=True, null=True, upload_to='kyc/documentos/')),
                ('selfie_verificacion', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('fecha_kyc', models.DateTimeField(blank=True, null=True)),
                ('comentarios_admin', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
