# Generated by Django 5.2.3 on 2026-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='metodo_certificacion',
            field=models.CharField(choices=[('FIRMA_VIRTUAL', 'Contrato Legal (FirmaVirtual)'), ('SMART_CONTRACT', 'Título Digital (Smart Contract) - Próximamente')], default='FIRMA_VIRTUAL', help_text='Elija cómo desea certificar su propiedad', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Dirección de billetera (Opcional)', max_length=100, null=True),
        ),
    ]
