# Generated by Django 5.2.3 on 2026-02-11 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_userprofile_metodo_certificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='compliance_status',
            field=models.CharField(choices=[('NONE', 'Sin revisión'), ('DRAFT', 'Borrador'), ('REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='NONE', help_text='Estado de revisión/compliance del proyecto.', max_length=10),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='data_room_url',
            field=models.URLField(blank=True, help_text='Enlace al Data Room del proyecto (Google Drive, Notion, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='docs_manifest_hash',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 del manifiesto de documentos (Due Diligence).', max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='docs_status',
            field=models.CharField(choices=[('MISSING', 'Documentos Faltantes'), ('PARTIAL', 'Documentación Parcial'), ('COMPLETE', 'Documentación Completa')], default='MISSING', help_text='Estado de la documentación legal del proyecto.', max_length=10),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gps_data',
            field=models.JSONField(blank=True, default=dict, help_text='Coordenadas GPS del activo. Ej: {"lat": -43.77, "lng": -71.69}', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='legal_hash',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 del paquete contractual/legal del proyecto.', max_length=128),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario dueño del proyecto (solo para proyectos EXTERNAL).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='owner_type',
            field=models.CharField(choices=[('INTERNAL', 'Proyecto Interno (Premium)'), ('EXTERNAL', 'Proyecto Externo (Marketplace)')], default='INTERNAL', help_text='INTERNAL = Proyecto propio (Joan). EXTERNAL = Proyecto de un Fraccionador externo.', max_length=10),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='spv_legal_name',
            field=models.CharField(blank=True, default='', help_text='Nombre legal del SPV/Sociedad dueña del activo (ej: Refugio Patagonia SpA).', max_length=200),
        ),
    ]
