# Generated by Django 5.2.3 on 2026-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_userprofile_metodo_certificacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="contrato_firmado",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="firmavirtual_files_ids",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="firmavirtual_id",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="firmavirtual_status",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="firmavirtual_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="metodo_certificacion",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="RUT del comprador (Persona o Rep. Legal)",
                max_length=20,
                null=True,
                verbose_name="RUT",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
