# Generated by Django 5.2.3 on 2026-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_proyecto_compliance_status_proyecto_data_room_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_docs',
            field=models.FileField(blank=True, help_text='Escritura o Constitución de la empresa (PDF)', null=True, upload_to='kyb/docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_legal_rep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Empresa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyb_status',
            field=models.CharField(choices=[('NONE', 'No Iniciado'), ('REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='NONE', help_text='Estado de verificación de empresa (solo para Fraccionadores).', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('INVESTOR', 'Inversionista'), ('FRACTIONALIZER', 'Fraccionador (Vendedor)')], default='INVESTOR', help_text='Rol del usuario en la plataforma.', max_length=20),
        ),
    ]
