# Generated by Django 5.2.3 on 2026-07-18 11:02

from django.db import migrations, models


def convertir_crypto_manual(apps, schema_editor):
    Reserva = apps.get_model("booking", "Reserva")
    Reserva.objects.filter(metodo_pago="CRYPTO_MANUAL").update(metodo_pago="CRYPTO")


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_eliminar_firmavirtual"),
    ]

    operations = [
        migrations.RunPython(convertir_crypto_manual, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reserva",
            name="metodo_pago",
            field=models.CharField(
                choices=[("MP", "Mercado Pago"), ("CRYPTO", "Cripto")],
                default="MP",
                max_length=15,
                verbose_name="Método de Pago",
            ),
        ),
    ]
