# Generated by Django 5.2.3 on 2026-07-18 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_eliminar_cryptomkt_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cryptomus_uuid",
            field=models.CharField(
                blank=True,
                help_text="UUID del invoice en Cryptomus",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="kushki_token",
            field=models.CharField(
                blank=True, help_text="Token de transacción Kushki", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="mp_payment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID de pago en MercadoPago",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="tx_hash",
            field=models.CharField(
                blank=True, help_text="Hash de la transacción de mint", max_length=66
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL amigable (ej: refugio-patagonia). Se genera sola si se deja vacío.",
                unique=True,
            ),
        ),
    ]
