# Generated by Django 5.2.3 on 2026-02-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_userprofile_company_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='archivo_propiedad',
            field=models.FileField(blank=True, help_text='Escritura o Certificado de Dominio Vigente para validar propiedad.', null=True, upload_to='proyectos/legal/'),
        ),
    ]
