# Generated by Django 5.2.3 on 2026-02-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_proyecto_archivo_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del drop (ej: "Drop #1 - Early Bird", "Drop #2 - Público")', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción corta del drop (ej: "Precio especial para los primeros inversores")')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora en que se abre la venta (UTC o timezone del proyecto)')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora en que se cierra la venta')),
                ('tokens_disponibles_drop', models.PositiveIntegerField(default=100, help_text='Cantidad de tokens disponibles SOLO en este drop')),
                ('tokens_vendidos_drop', models.PositiveIntegerField(default=0, help_text='Tokens vendidos durante este drop (se actualiza automáticamente)')),
                ('precio_override', models.PositiveIntegerField(blank=True, help_text='Precio especial para este drop (deja vacío para usar el precio del proyecto)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, el drop no se muestra aunque esté en rango de fechas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece este Drop.', on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='booking.proyecto')),
            ],
            options={
                'verbose_name': 'Drop (Ventana de Venta)',
                'verbose_name_plural': 'Drops (Ventanas de Venta)',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
