# Generated by Django 5.1.15 on 2026-07-18 11:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_grupos_y_perfiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LISTING", "Listing/Originación"),
                            ("TRANSACCION", "Transacción"),
                            ("ADMIN", "Administración anual"),
                            ("CASHOUT", "Retiro/Cash-out"),
                            ("PREMIUM", "Servicio premium"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "monto_minimo_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "cap_creditos_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento_fees_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "descuento_creditos_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("kyc_requerido", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["tier"],
            },
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="rentabilidad_estimada",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="docs_manifest_hash",
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="gps_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="legal_hash",
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Interno (Joan)"),
                    ("EXTERNAL", "Externo (Fraccionador)"),
                ],
                default="INTERNAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="spv_legal_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tokens_vendidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="venta_solo_drops",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, solo se puede comprar con Drop activo",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="didit_session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="investment_total_usd",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kyc_tier",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kyc_verificado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuracion",
            name="precio_base_token",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                max_digits=12,
                verbose_name="Precio Base Token (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="precio_token",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                help_text="Precio por token en USD",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_REVISION", "En revisión"),
                    ("CONFIRMADO", "Confirmado"),
                    ("RECHAZADO", "Rechazado"),
                    ("FALLIDO", "Fallido"),
                    ("REEMBOLSADO", "Reembolsado"),
                ],
                default="PENDIENTE",
                max_length=15,
                verbose_name="Estado de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("MP", "MercadoPago"),
                    ("CRYPTO", "Cryptomus"),
                    ("KUSHKI", "Kushki"),
                    ("CREDITO", "Créditos RWA"),
                ],
                default="MP",
                max_length=15,
                verbose_name="Método de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("objeto_tipo", models.CharField(max_length=50)),
                ("objeto_id", models.IntegerField(null=True)),
                ("datos_antes", models.JSONField(null=True)),
                ("datos_despues", models.JSONField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["accion", "created_at"],
                        name="booking_aud_accion_f20eb6_idx",
                    ),
                    models.Index(
                        fields=["objeto_tipo", "objeto_id"],
                        name="booking_aud_objeto__64b5d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("tier", models.IntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("extended", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at", "tier"],
                        name="booking_cre_expires_6813e6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra de créditos"),
                            ("USO", "Uso en checkout"),
                            ("EXPIRACION", "Expiración automática"),
                            ("EXTENSION", "Extensión a 18 meses"),
                            ("DEVOLUCION", "Devolución por pago fallido"),
                            ("AJUSTE", "Ajuste manual por Joan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="booking.reserva",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="booking_cre_user_id_f8d264_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FraccionadorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kyb_estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente revisión"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("MAS_DOCS", "Requiere más documentos"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERSONA", "Persona natural"),
                            ("EMPRESA", "Empresa"),
                        ],
                        default="PERSONA",
                        max_length=10,
                    ),
                ),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("rut_empresa", models.CharField(blank=True, max_length=12)),
                (
                    "doc_dominio_vigente",
                    models.FileField(blank=True, null=True, upload_to="kyb/dominios/"),
                ),
                (
                    "doc_escritura",
                    models.FileField(
                        blank=True, null=True, upload_to="kyb/escrituras/"
                    ),
                ),
                (
                    "doc_tasacion",
                    models.FileField(
                        blank=True, null=True, upload_to="kyb/tasaciones/"
                    ),
                ),
                (
                    "tokens_reserve_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                ("banco", models.CharField(blank=True, max_length=100)),
                ("cuenta_bancaria", models.CharField(blank=True, max_length=50)),
                ("tipo_cuenta", models.CharField(blank=True, max_length=20)),
                ("kyb_fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("kyb_notas", models.TextField(blank=True)),
                (
                    "kyb_revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyb_revisiones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraccionador_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kyb_estado"], name="booking_fra_kyb_est_dd2356_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("stock_total", models.IntegerField()),
                ("stock_disponible", models.IntegerField()),
                (
                    "precio_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("activo", models.BooleanField(default=False)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drops",
                        to="booking.proyecto",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["proyecto", "activo"],
                        name="booking_pro_proyect_cd64ce_idx",
                    )
                ],
                "unique_together": {("proyecto", "numero")},
            },
        ),
    ]
