# Generated by Django 5.2.3 on 2026-02-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_add_project_drop_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdrop',
            name='max_tokens_por_usuario',
            field=models.PositiveIntegerField(blank=True, help_text='Máx. tokens que un solo usuario puede comprar en este Drop. Vacío = sin límite.', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='venta_solo_drops',
            field=models.BooleanField(default=False, help_text='Si está activado, solo se puede comprar cuando hay un Drop activo. Si no hay Drop abierto, el proyecto queda bloqueado.', verbose_name='Venta solo vía Drops'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='drop',
            field=models.ForeignKey(blank=True, help_text='Drop en el que se realizó esta compra (para auditoría y métricas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='booking.projectdrop'),
        ),
    ]
