# Generated by Django 5.2.3 on 2026-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_drops_cerrojo_antiballena_trazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investment_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total invertido acumulado (USD)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nivel 0 (Básico - $500)'), (1, 'Nivel 1 (Verificado - $10k)'), (2, 'Nivel 2 (Whale - Ilimitado)')], default=0, help_text='Nivel de verificación actual'),
        ),
    ]
