# Generated by Django 5.1.15 on 2026-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0025_s2_modelos_nuevos"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
