# Generated by Django 5.1.15 on 2026-07-25 06:23

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0027_s2_fixtures_tiers_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraccionadorprofile",
            name="doc_dominio_vigente",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyb_dominios,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="fraccionadorprofile",
            name="doc_escritura",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyb_escrituras,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="fraccionadorprofile",
            name="doc_tasacion",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyb_tasaciones,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_portada",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_proyectos,
                validators=[booking.validators.validar_imagen],
            ),
        ),
        migrations.AlterField(
            model_name="proyectodocumento",
            name="archivo",
            field=models.FileField(
                upload_to=booking.validators.ruta_proyectos_documentos,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="proyectoimagen",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_proyectos_galeria,
                validators=[booking.validators.validar_imagen],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="documento_identidad_frontal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyc_documentos,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="documento_identidad_reverso",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyc_documentos,
                validators=[booking.validators.validar_archivo_kyc],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="selfie_verificacion",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=booking.validators.ruta_kyc_selfies,
                validators=[booking.validators.validar_imagen],
            ),
        ),
    ]
